spring:
  application:
    name: rabnbserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/BNB
    username: root
    password: 123456789
    hikari:
      minimum-idle: 50
      maximum-pool-size: 150
      auto-commit: true
      idle-timeout: 30000
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  data:
    redis:
      database: 4
      host: 127.0.0.1
      port: 6379
      # password:
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  threads:
    virtual:
      enabled: true
server:
  port: 8080
# Sa-Token 配置
sa-token:
  token-name: Account-token
  timeout: 86400
  is-read-header: true
  is-read-body: true
  is-read-cookie: true
