spring:
  application:
    name: rabnbserver
  jackson:
    # 设置全局日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.110.104:3306/BNB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456789
    hikari:
      minimum-idle: 50
      maximum-pool-size: 150
      auto-commit: true
      idle-timeout: 30000
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        serverTimezone: Asia/Shanghai
  data:
    redis:
      database: 4
      host: 192.168.110.104
      port: 6379
      # password:
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  threads:
    virtual:
      enabled: true
  mail:
    host: 'smtp.sina.cn'
    port: 465
    username: 'hun422@sina.com'
    password: 'f00eb3c619a07f36'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
server:
  port: 8080


ADMIN:
  USERNAME: ADMIN
  PASSWORD: admin
  DFCODE: eC4vW8
# Sa-Token 配置
sa-token:
  token-name: Account-token
  timeout: 86400
  is-read-header: true
  is-read-body: true
  is-read-cookie: true

# 区块链配置（BSC Mainnet）
blockchain:
#  rpc-url: https://bsc-dataseed.binance.org
#  # 备用 RPC:
#  # https://bsc-dataseed1.defibit.io
#  # https://bsc-dataseed1.ninicoin.io
#  chain-id: 56
#  currency-symbol: BNB
#  gas-limit-default: 1000000
#  tx-poll-interval-ms: 2000
#  tx-timeout-ms: 1200000
  rpc-url: https://data-seed-prebsc-1-s1.bnbchain.org:8545
  # 备用 RPC:
  # https://bsc-dataseed1.defibit.io
  # https://bsc-dataseed1.ninicoin.io
  chain-id: 97
  currency-symbol: tBNB
  gas-limit-default: 10000000
  tx-poll-interval-ms: 2000
  tx-timeout-ms: 1200000

# 合约管理员私钥密文（Base64: iv:cipher）
contract:
  admin:
#    private-key-enc: lSS2qVjGBBn4gDHxk7Tf2A==:E7655itX9jc4rLs+uATtYaW1VaaEl9/xzEs5G2DEzaxp0uWK6zqEvMzhuwaJirzXvG4Dj+BRDlONXjYKyD3Gv/EmJUpckzs/8ohlU3RJ8gY=
      private-key-enc: JVi8ghscqA/EcrGTcrGv3A==:lbDOqnZsiIJQRgEXU/To7uRGGPBsUcgk3XGdh1J8W+UnHCnbe9MhQEuiSXxtJlK62YMWCN1sxjhkEJtGIrz4mU/7tRv4W8ekLY6aG6TiTes=
  address:
    payment-usdt: '0x600F50058c8cEb5Ad9448c82eA3135d4C5539b12'
    card-nft: '0xCD4e15BC04c2A71950D9c18A4b44D7C10116d0E0'
    aion: '0x308FFf70b39d3C7D00196344916714433b806AA8'

# 异常重试框架配置
abnormal:
  retry:
    # 轮询间隔（秒）
    scan-interval-seconds: 10
    # 是否启用邮件通知
    mail-enabled: true
    # 发件人邮箱
    mail-from: 'hun422@sina.com'
    # 收件人邮箱列表
    mail-to: [xxsxxas@gmail.com]

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
